dist: trusty
sudo: required

notifications:
    email: false

services:
  - docker

script:
    # Standard build
    - BUILD_ARGS="--no-cache" make build

after_success:
    - TRAVIS_BRANCH=$TRAVIS_BRANCH make push
